In [1]:
import numpy as np

Creating np list

In [2]:
mylist = [1,2,3]

In [3]:
myarr = np.array(mylist)

In [4]:
myarr

array([1, 2, 3])

In [5]:
type(myarr)

numpy.ndarray

Creating 2d array

In [11]:
mymatrix = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
mymatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
ndarr = np.array(mymatrix)

In [14]:
ndarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
type(ndarr)

numpy.ndarray

Buidin functions and methods of np

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,100,9)

array([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [22]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [24]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [25]:
#for identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Random distributions of data

In [28]:
np.random.rand(1)

array([0.73715515])

In [29]:
np.random.rand(5,2)

array([[0.85959419, 0.29085913],
       [0.28746268, 0.44261263],
       [0.09831949, 0.58643741],
       [0.75246037, 0.15743185],
       [0.26423498, 0.85995753]])

In [33]:
'''randn is standard normal distribution ,note::This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.
'''

np.random.randn(5)

array([-1.3725329 ,  0.13555779, -0.23425124, -0.67806661,  0.74487518])

In [35]:
np.random.randn(2,3)

array([[-0.29369875, -0.2072595 ,  0.57525042],
       [ 0.02227187,  0.54163298, -0.28565436]])

In [37]:
np.random.randint(0,101,5) #getting 5 random no bw 0,101

array([38,  6, 55,  2, 85])

In [38]:
np.random.randint(0,101,(3,4)) #getting 3,4 random no matrix

array([[92, 34, 19, 21],
       [91, 98, 94, 76],
       [82, 76, 60, 21]])

In [42]:
np.random.seed(46) #setting any seed value for geting name random no
np.random.rand(4)

array([0.78383235, 0.63483371, 0.24904309, 0.75807586])

In [44]:
np.random.seed(46) 
np.random.rand(3)

array([0.78383235, 0.63483371, 0.24904309])

Reshaping

In [47]:
arr = np.arange(9)

In [48]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Method calls

In [51]:
ran_arr = np.random.randint(0,101,10)

In [52]:
ran_arr

array([18, 75, 93, 60, 27, 80,  2, 72, 32, 31])

In [53]:
ran_arr.max()

93

In [54]:
ran_arr.min()

2

In [55]:
#to get index of min max no use arg
ran_arr.argmax()

2

In [56]:
ran_arr.argmin()

6

In [57]:
ran_arr.dtype

dtype('int32')

In [58]:
myarr = np.linspace(0,10,101)

In [59]:
myarr

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])