In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[:1]

array([0])

Broadcasting and selecting a part of array|

In [8]:
slice_arr = arr[:5]

In [9]:
slice_arr

array([0, 1, 2, 3, 4])

In [10]:
slice_arr[:] = 46

In [11]:
slice_arr

array([46, 46, 46, 46, 46])

In [12]:
arr

array([46, 46, 46, 46, 46,  5,  6,  7,  8,  9, 10])

In [13]:
#in this method slice of array is originally pointing to main arr
#hence change to slice results in change of main arr

now another way in which above repition does'nt happen is

In [14]:
arr_copy = arr.copy()

In [15]:
arr_copy

array([46, 46, 46, 46, 46,  5,  6,  7,  8,  9, 10])

In [16]:
arr_copy[:] = 99

In [17]:
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [18]:
arr

array([46, 46, 46, 46, 46,  5,  6,  7,  8,  9, 10])

In [19]:
#here no change to orignal array

Indexing on 2D arrays

In [21]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [22]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr_2d.shape

(3, 3)

In [24]:
arr_2d[1]

array([20, 25, 30])

In [25]:
arr_2d[1][2]    #to get 30

30

In [26]:
arr_2d[1,2]     #same as before

30

In [33]:
#to get a sub-matrix
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

Conditional selection array

In [34]:
arr = np.arange(0,11)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
bool_arr = arr > 4

In [37]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [38]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

i.e.

In [39]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])